# Generated by Django 3.2.7 on 2021-10-07 04:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('tr', 'trash'), ('pr', 'paper'), ('mt', 'metal'), ('gl', 'glass'), ('pl', 'plastic'), ('cd', 'cardboard')], default='tr', max_length=2)),
                ('bin_capacity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='CollectionAccount',
            fields=[
                ('owner_name', models.CharField(max_length=200)),
                ('company_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('truck_capacity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='PlantAccount',
            fields=[
                ('owner_name', models.CharField(max_length=200)),
                ('company_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAccount',
            fields=[
                ('owner_name', models.CharField(max_length=200)),
                ('company_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_full', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('scan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanners.bin')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('lat', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lon', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanners.propertyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanners.bin')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanners.collectionaccount')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanners.plantaccount')),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanners.property'),
        ),
    ]
